language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio lib install 622 # http://platformio.org/lib/show/622/AStar32U4

env:
- BOARD=leonardo
- BOARD=micro
- BOARD=yun

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib="." $e/*;
  done
